# Generated by Django 5.0.6 on 2026-06-29 19:32

import apps.faceai.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_w', models.FloatField()),
                ('bbox_h', models.FloatField()),
                ('detection_score', models.FloatField()),
                ('embedding', apps.faceai.models.FaceEmbeddingField()),
                ('embedding_dim', models.PositiveSmallIntegerField(default=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='photos.photo')),
            ],
            options={
                'db_table': 'face_embeddings',
            },
        ),
        migrations.CreateModel(
            name='Selfie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='selfies/%Y/%m/')),
                ('embedding', apps.faceai.models.FaceEmbeddingField()),
                ('embedding_dim', models.PositiveSmallIntegerField(default=512)),
                ('detection_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('matched', 'Matched'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfies', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'selfies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('face_embedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='faceai.faceembedding')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='photos.photo')),
                ('selfie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='faceai.selfie')),
            ],
            options={
                'db_table': 'face_matches',
                'ordering': ['-similarity'],
            },
        ),
        migrations.AddIndex(
            model_name='faceembedding',
            index=models.Index(fields=['photo'], name='face_embedd_photo_i_eca2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='facematch',
            index=models.Index(fields=['selfie', 'similarity'], name='face_matche_selfie__848ecb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facematch',
            unique_together={('selfie', 'photo', 'face_embedding')},
        ),
    ]
